#!/usr/bin/env bash
# Write a script that:
# Create file /var/run/holbertonscript.pid
# containing its PID.
# Displays "To infinity and beyond" indefinitely.
# Displays "I hate the kill command" on SIGTERM signal.
# Displays "Y U no love me?!" on SIGINT signal.
# Deletes the pid file and terminates on SIGQUIT or SIGTERM signal.

rmfile_n_exit()
{
    rm -f /var/run/myscript.pid;
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGTERM
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGQUIT


echo $$ >> /var/run/myscript.pid
while (true)
do
    echo 'To infinity and beyond'
    sleep 2
done
